# Generated by Django 5.1.3 on 2024-12-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armani', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
