# Generated by Django 5.1.3 on 2024-12-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armani', '0002_alter_mentor_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='looking_for',
            field=models.ManyToManyField(blank=True, to='armani.services'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='armani.label'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
