# Generated by Django 5.1.3 on 2024-12-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armani', '0003_customuser_looking_for_mentor_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Photo',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='projects', to='armani.label'),
        ),
    ]
