# Generated by Django 5.1.3 on 2024-12-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armani', '0004_alter_customuser_photo_alter_project_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='social_networks',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='identification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
