# Generated by Django 5.1.3 on 2024-12-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armani', '0005_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='looking_for',
            field=models.ManyToManyField(to='armani.services'),
        ),
    ]
