# Generated by Django 5.1.3 on 2024-12-22 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armani', '0005_mentor_city_mentor_country_mentor_social_networks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='img',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='photo',
        ),
    ]
