# Generated by Django 5.1.3 on 2024-12-03 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armani', '0006_alter_clients_looking_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('name', models.CharField(choices=[('FR', 'کشاورزی'), ('SD', 'توسعه نرم افزار'), ('AI', 'هوش مصنوعی')], max_length=2)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_mentor',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rate', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, default='Site/Mamozio.png', upload_to='image/')),
                ('date_of_start', models.DateField(auto_now_add=True)),
                ('date_of_end', models.DateField(blank=True, null=True)),
                ('labels', models.ManyToManyField(to='armani.label')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
