# Generated by Django 5.1.3 on 2024-12-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armani', '0007_remove_customuser_is_mentor_customuser_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
