# Generated by Django 5.1.3 on 2024-12-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armani', '0007_label_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
