# Generated by Django 5.1.3 on 2024-12-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armani', '0008_alter_customuser_is_mentor_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(),
        ),
    ]
