# Generated by Django 5.1.3 on 2024-12-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armani', '0010_project_manager_alter_mentor_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(),
        ),
    ]
